name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        shell: bash
        run: |
          ls -la
          ls -la contact-manager
          cd contact-manager
          npm ci

      - name: Build
        shell: bash
        run: |
          cd contact-manager
          npm run build

      - name: Deploy to GitHub Pages
        shell: bash
        working-directory: contact-manager
        run: |
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/githady/guruji.git
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
